-- RestoGuard multi-tenant SaaS schema.
-- Ejecutar en Supabase SQL Editor.
-- Flujo:
-- 1. Crear tu usuario en Supabase Auth.
-- 2. Ejecutar este SQL.
-- 3. Reemplazar el correo y ejecutar:
--
-- insert into public.app_admins (user_id, email)
-- select id, email
-- from auth.users
-- where lower(email) = lower('TU_CORREO_AQUI')
-- on conflict (user_id) do update set email = excluded.email;

create extension if not exists pgcrypto;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.negocios (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  nombre text not null,
  rubro text,
  ciudad text,
  estado text not null default 'BETA' check (estado in ('BETA', 'ACTIVO', 'SUSPENDIDO')),
  plan text not null default 'BETA',
  beta_started_at timestamp with time zone not null default now(),
  trial_ends_at timestamp with time zone not null default (now() + interval '30 days'),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.negocio_usuarios (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  rol text not null default 'ADMIN' check (
    rol in ('ADMIN', 'SUPERVISOR', 'CAJA', 'MOZO', 'COCINA', 'BARRA', 'RRHH')
  ),
  created_at timestamp with time zone not null default now(),
  unique (negocio_id, user_id)
);

create table if not exists public.insumos (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  codigo text,
  nombre text not null,
  categoria text,
  unidad text not null default 'und',
  stock numeric not null default 0 check (stock >= 0),
  stock_minimo numeric not null default 0 check (stock_minimo >= 0),
  costo_unitario numeric not null default 0 check (costo_unitario >= 0),
  vencimiento date,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.mesas (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  nombre text not null,
  zona text,
  estado text not null default 'LIBRE' check (estado in ('LIBRE', 'OCUPADA', 'RESERVADA')),
  pax int not null default 0,
  capacidad int not null default 4,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  nombre text not null,
  categoria text,
  area text not null default 'COCINA' check (area in ('COCINA', 'BARRA')),
  precio numeric not null default 0 check (precio >= 0),
  costo numeric not null default 0 check (costo >= 0),
  activo boolean not null default true,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  mesa_id bigint references public.mesas(id) on delete set null,
  codigo text not null,
  canal text not null default 'SALON',
  estado text not null default 'PENDIENTE' check (
    estado in ('PENDIENTE', 'EN_COCINA', 'LISTO', 'SERVIDO', 'COBRADO', 'ANULADO')
  ),
  responsable text,
  total numeric not null default 0 check (total >= 0),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  nombre text not null,
  area text not null default 'COCINA' check (area in ('COCINA', 'BARRA')),
  cantidad numeric not null default 1 check (cantidad > 0),
  precio numeric not null default 0 check (precio >= 0),
  estado text not null default 'PENDIENTE' check (
    estado in ('PENDIENTE', 'PREPARANDO', 'LISTO', 'ANULADO')
  ),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.compras (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  proveedor text,
  descripcion text not null,
  total numeric not null default 0 check (total >= 0),
  comprobante text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.mermas (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  insumo_id bigint references public.insumos(id) on delete set null,
  descripcion text not null,
  cantidad numeric not null check (cantidad > 0),
  unidad text not null default 'und',
  causa text not null,
  costo numeric not null default 0 check (costo >= 0),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.empleados (
  id bigint generated by default as identity primary key,
  negocio_id bigint not null references public.negocios(id) on delete cascade,
  nombre text not null,
  rol text not null default 'MOZO',
  email text,
  telefono text,
  sueldo numeric not null default 0 check (sueldo >= 0),
  estado text not null default 'ACTIVO' check (estado in ('ACTIVO', 'OBSERVACION', 'INACTIVO')),
  created_at timestamp with time zone not null default now()
);

alter table public.negocio_usuarios
  drop constraint if exists negocio_usuarios_rol_check;

alter table public.negocio_usuarios
  add constraint negocio_usuarios_rol_check
  check (rol in ('ADMIN', 'SUPERVISOR', 'CAJA', 'MOZO', 'COCINA', 'BARRA', 'RRHH'));

alter table public.mesas
  add column if not exists capacidad int not null default 4;

create index if not exists app_admins_email_idx on public.app_admins (lower(email));
create index if not exists negocios_owner_idx on public.negocios (owner_id);
create index if not exists negocios_estado_idx on public.negocios (estado);
create index if not exists negocio_usuarios_user_idx on public.negocio_usuarios (user_id);
create index if not exists negocio_usuarios_negocio_idx on public.negocio_usuarios (negocio_id);
create index if not exists insumos_negocio_idx on public.insumos (negocio_id);
create index if not exists mesas_negocio_idx on public.mesas (negocio_id);
create index if not exists productos_negocio_idx on public.productos (negocio_id);
create index if not exists pedidos_negocio_fecha_idx on public.pedidos (negocio_id, created_at desc);
create index if not exists pedido_items_negocio_idx on public.pedido_items (negocio_id);
create index if not exists compras_negocio_fecha_idx on public.compras (negocio_id, created_at desc);
create index if not exists mermas_negocio_fecha_idx on public.mermas (negocio_id, created_at desc);
create index if not exists empleados_negocio_idx on public.empleados (negocio_id);

create or replace function public.es_super_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_admins aa
    where aa.user_id = auth.uid()
  );
$$;

create or replace function public.es_miembro_negocio(p_negocio_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.es_super_admin()
    or exists (
      select 1
      from public.negocio_usuarios nu
      where nu.negocio_id = p_negocio_id
        and nu.user_id = auth.uid()
    );
$$;

create or replace function public.negocio_habilitado(p_negocio_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.es_super_admin()
    or exists (
      select 1
      from public.negocios n
      where n.id = p_negocio_id
        and n.estado in ('BETA', 'ACTIVO')
    );
$$;

create or replace function public.tiene_acceso_negocio(p_negocio_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.es_miembro_negocio(p_negocio_id)
    and public.negocio_habilitado(p_negocio_id);
$$;

create or replace function public.es_admin_negocio(p_negocio_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.es_super_admin()
    or exists (
      select 1
      from public.negocio_usuarios nu
      join public.negocios n on n.id = nu.negocio_id
      where nu.negocio_id = p_negocio_id
        and nu.user_id = auth.uid()
        and nu.rol = 'ADMIN'
        and n.estado in ('BETA', 'ACTIVO')
    );
$$;

alter table public.app_admins enable row level security;
alter table public.negocios enable row level security;
alter table public.negocio_usuarios enable row level security;
alter table public.insumos enable row level security;
alter table public.mesas enable row level security;
alter table public.productos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;
alter table public.compras enable row level security;
alter table public.mermas enable row level security;
alter table public.empleados enable row level security;

drop policy if exists "app_admins_select_self" on public.app_admins;
create policy "app_admins_select_self"
  on public.app_admins for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "negocios_select_miembro" on public.negocios;
create policy "negocios_select_miembro"
  on public.negocios for select
  to authenticated
  using (
    public.es_super_admin()
    or owner_id = auth.uid()
    or public.es_miembro_negocio(id)
  );

drop policy if exists "negocios_insert_admin" on public.negocios;
create policy "negocios_insert_admin"
  on public.negocios for insert
  to authenticated
  with check (public.es_super_admin());

drop policy if exists "negocios_update_admin" on public.negocios;
create policy "negocios_update_admin"
  on public.negocios for update
  to authenticated
  using (public.es_admin_negocio(id))
  with check (public.es_admin_negocio(id));

drop policy if exists "negocio_usuarios_select_miembro" on public.negocio_usuarios;
create policy "negocio_usuarios_select_miembro"
  on public.negocio_usuarios for select
  to authenticated
  using (user_id = auth.uid() or public.es_miembro_negocio(negocio_id));

drop policy if exists "negocio_usuarios_insert_admin" on public.negocio_usuarios;
create policy "negocio_usuarios_insert_admin"
  on public.negocio_usuarios for insert
  to authenticated
  with check (public.es_admin_negocio(negocio_id));

drop policy if exists "negocio_usuarios_update_admin" on public.negocio_usuarios;
create policy "negocio_usuarios_update_admin"
  on public.negocio_usuarios for update
  to authenticated
  using (public.es_admin_negocio(negocio_id))
  with check (public.es_admin_negocio(negocio_id));

drop policy if exists "negocio_usuarios_delete_admin" on public.negocio_usuarios;
create policy "negocio_usuarios_delete_admin"
  on public.negocio_usuarios for delete
  to authenticated
  using (public.es_admin_negocio(negocio_id));

drop policy if exists "insumos_crud_miembro" on public.insumos;
create policy "insumos_crud_miembro"
  on public.insumos for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "mesas_crud_miembro" on public.mesas;
create policy "mesas_crud_miembro"
  on public.mesas for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "productos_crud_miembro" on public.productos;
create policy "productos_crud_miembro"
  on public.productos for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "pedidos_crud_miembro" on public.pedidos;
create policy "pedidos_crud_miembro"
  on public.pedidos for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "pedido_items_crud_miembro" on public.pedido_items;
create policy "pedido_items_crud_miembro"
  on public.pedido_items for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "compras_crud_miembro" on public.compras;
create policy "compras_crud_miembro"
  on public.compras for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "mermas_crud_miembro" on public.mermas;
create policy "mermas_crud_miembro"
  on public.mermas for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

drop policy if exists "empleados_crud_miembro" on public.empleados;
create policy "empleados_crud_miembro"
  on public.empleados for all
  to authenticated
  using (public.tiene_acceso_negocio(negocio_id))
  with check (public.tiene_acceso_negocio(negocio_id));

create or replace function public.listar_negocios_admin()
returns table (
  id bigint,
  nombre text,
  rubro text,
  ciudad text,
  estado text,
  plan text,
  owner_id uuid,
  owner_email text,
  beta_started_at timestamp with time zone,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone,
  usuarios bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.es_super_admin() then
    raise exception 'Solo el Super Admin puede listar negocios';
  end if;

  return query
    select
      n.id,
      n.nombre,
      n.rubro,
      n.ciudad,
      n.estado,
      n.plan,
      n.owner_id,
      u.email::text as owner_email,
      n.beta_started_at,
      n.trial_ends_at,
      n.created_at,
      count(nu.id)::bigint as usuarios
    from public.negocios n
    left join auth.users u on u.id = n.owner_id
    left join public.negocio_usuarios nu on nu.negocio_id = n.id
    group by n.id, u.email
    order by n.created_at desc;
end;
$$;

create or replace function public.crear_negocio_admin(
  p_nombre text,
  p_rubro text,
  p_ciudad text,
  p_owner_email text
)
returns table (
  id bigint,
  nombre text,
  owner_email text,
  trial_ends_at timestamp with time zone
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid;
  v_owner_email text;
  v_negocio public.negocios;
begin
  if not public.es_super_admin() then
    raise exception 'Solo el Super Admin puede crear negocios';
  end if;

  if nullif(trim(p_nombre), '') is null then
    raise exception 'El nombre del negocio es obligatorio';
  end if;

  select au.id, au.email::text
    into v_owner_id, v_owner_email
  from auth.users au
  where lower(au.email) = lower(trim(p_owner_email))
  limit 1;

  if v_owner_id is null then
    raise exception 'Usuario no encontrado. Primero crealo en Supabase Auth.';
  end if;

  insert into public.negocios (
    owner_id,
    nombre,
    rubro,
    ciudad,
    estado,
    plan,
    beta_started_at,
    trial_ends_at
  )
  values (
    v_owner_id,
    trim(p_nombre),
    nullif(trim(p_rubro), ''),
    nullif(trim(p_ciudad), ''),
    'BETA',
    'BETA',
    now(),
    now() + interval '30 days'
  )
  returning * into v_negocio;

  insert into public.negocio_usuarios (
    negocio_id,
    user_id,
    email,
    rol
  )
  values (
    v_negocio.id,
    v_owner_id,
    lower(v_owner_email),
    'ADMIN'
  )
  on conflict (negocio_id, user_id)
  do update set
    email = excluded.email,
    rol = 'ADMIN';

  return query
    select
      v_negocio.id,
      v_negocio.nombre,
      lower(v_owner_email)::text,
      v_negocio.trial_ends_at;
end;
$$;

create or replace function public.actualizar_estado_negocio(
  p_negocio_id bigint,
  p_estado text
)
returns table (
  id bigint,
  estado text,
  plan text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estado text := upper(trim(p_estado));
  v_negocio public.negocios;
begin
  if not public.es_super_admin() then
    raise exception 'Solo el Super Admin puede cambiar el estado comercial';
  end if;

  if v_estado not in ('BETA', 'ACTIVO', 'SUSPENDIDO') then
    raise exception 'Estado comercial invalido';
  end if;

  update public.negocios n
    set estado = v_estado,
        plan = case
          when v_estado = 'BETA' then 'BETA'
          when v_estado = 'ACTIVO' and n.plan = 'BETA' then 'BASICO'
          else n.plan
        end
  where n.id = p_negocio_id
  returning * into v_negocio;

  if v_negocio.id is null then
    raise exception 'Negocio no encontrado';
  end if;

  return query select v_negocio.id, v_negocio.estado, v_negocio.plan;
end;
$$;

create or replace function public.agregar_usuario_negocio(
  p_negocio_id bigint,
  p_email text,
  p_rol text default 'MOZO'
)
returns table (
  id bigint,
  email text,
  rol text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_user_email text;
  v_member public.negocio_usuarios;
begin
  if not public.es_admin_negocio(p_negocio_id) then
    raise exception 'Solo un ADMIN puede agregar usuarios';
  end if;

  if p_rol not in ('ADMIN', 'SUPERVISOR', 'CAJA', 'MOZO', 'COCINA', 'BARRA', 'RRHH') then
    raise exception 'Rol invalido';
  end if;

  select au.id, au.email::text
    into v_user_id, v_user_email
  from auth.users au
  where lower(au.email) = lower(trim(p_email))
  limit 1;

  if v_user_id is null then
    raise exception 'Usuario no encontrado. Primero crealo en Supabase Auth.';
  end if;

  insert into public.negocio_usuarios (
    negocio_id,
    user_id,
    email,
    rol
  )
  values (
    p_negocio_id,
    v_user_id,
    lower(v_user_email),
    p_rol
  )
  on conflict (negocio_id, user_id)
  do update set
    email = excluded.email,
    rol = excluded.rol
  returning * into v_member;

  return query
    select
      v_member.id,
      v_member.email::text,
      v_member.rol::text;
end;
$$;

grant execute on function public.es_super_admin() to authenticated;
grant execute on function public.listar_negocios_admin() to authenticated;
grant execute on function public.crear_negocio_admin(text, text, text, text) to authenticated;
grant execute on function public.actualizar_estado_negocio(bigint, text) to authenticated;
grant execute on function public.agregar_usuario_negocio(bigint, text, text) to authenticated;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
